
name: CI

on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        type: string
      app_roles:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init --backend-config="key=${{ github.event.inputs.app_name }}.tfstate" --backend-config="access_key=${{ secrets.SA_ACCESS_KEY }}"
        working-directory: ./ActionTestFlow/iac

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var='application_name=${{ github.event.inputs.app_name }}' -var='application_roles=${{ fromJSON(toJSON(github.event.inputs.app_roles)) }}'
        working-directory: ./ActionTestFlow/iac